flowchart LR
    x00 & x01 & x02 & x03 & x04 & x05 & x06 & x07 & x08 & x09 & x10 & x11 & x12 & x13 & x14 & x15 & x16 & x17 & x18 & x19 & x20 & x21 & x22 & x23 & x24 & x25 & x26 & x27 & x28 & x29 & x30 & x31 & x32 & x33 & x34 & x35 & x36 & x37 & x38 & x39 & x40 & x41 & x42 & x43 & x44 & y00 & y01 & y02 & y03 & y04 & y05 & y06 & y07 & y08 & y09 & y10 & y11 & y12 & y13 & y14 & y15 & y16 & y17 & y18 & y19 & y20 & y21 & y22 & y23 & y24 & y25 & y26 & y27 & y28 & y29 & y30 & y31 & y32 & y33 & y34 & y35 & y36 & y37 & y38 & y39 & y40 & y41 & y42 & y43 & y44

    bfc & kbv --> |AND| tts
    bjm & vkt --> |AND| wtr
    bjm & vkt --> |XOR| z19
    bmh & spk --> |AND| wrc
    bss & fch --> |AND| hkt
    bss & fch --> |XOR| z39
    bwc & fqk --> |AND| fvd
    bwc & fqk --> |XOR| z40
    cbq & kkt --> |AND| cdh
    cdh & rqv --> |OR| z45
    cdk & rmn --> |OR| nhs
    cfd & cqd --> |AND| pht
    cfd & cqd --> |XOR| z28
    cmd & pfk --> |AND| cqw
    cnp & ddh --> |OR| pjt
    cnv & jsj --> |AND| ddh
    cqw & wtc --> |OR| dnp
    cwn & pmt --> |AND| fgg
    cwn & pmt --> |XOR| z07
    cwr & fnk --> |AND| dtt
    ddr & wkn --> |AND| jsv
    ddr & wkn --> |XOR| z16
    dds & btb --> |OR| ddr
    dnw & dtt --> |OR| sdt
    dpm & pqq --> |OR| bfc
    dtk & ddn --> |OR| mkh
    dvb & wtv --> |OR| cdm
    fmn & kqh --> |XOR| z30
    fnk & cwr --> |XOR| z32
    fvd & rpm --> |OR| srq
    fvp & kgr --> |AND| vbr
    gqh & tcv --> |XOR| z20
    gqt & gnv --> |OR| rvb
    gtg & hvg --> |AND| wvn
    hdc & bfw --> |OR| vnn
    hjp & mhm --> |AND| jqs
    hjp & mhm --> |XOR| z17
    hkt & sms --> |OR| fqk
    hnj & ddt --> |OR| fmn
    hpm & nhq --> |OR| kkt
    hqh & qrt --> |OR| skd
    hsc & dpq --> |OR| mtq
    hsp & qnp --> |AND| dds
    hsp & qnp --> |XOR| z15
    htr & kdm --> |OR| vkt
    hvg & gtg --> |XOR| z10
    jhb & fgv --> |OR| hsp
    jmc & qkk --> |XOR| z29
    jmp & nqw --> |OR| vnw
    jpp & tpv --> |AND| vqk
    jpp & tpv --> |XOR| z06
    jsj & cnv --> |XOR| z23
    jsv & qsd --> |OR| hjp
    jtf & jdk --> |OR| ktj
    kbj & nsd --> |AND| hdc
    kbj & nsd --> |XOR| z13
    kbv & bfc --> |XOR| z42
    kgr & fvp --> |XOR| z09
    kkt & cbq --> |XOR| z44
    kqh & fmn --> |AND| dtk
    krm & vdc --> |AND| svv
    krm & vdc --> |XOR| z04
    ktj & dmh --> |AND| msm
    ktj & dmh --> |XOR| z38
    kwf & nbh --> |OR| sdh
    mds & cmn --> |OR| fnk
    mkh & tvs --> |AND| cmn
    mmr & cgr --> |AND| vrk
    mmr & cgr --> |XOR| z05
    msm & gcn --> |OR| fch
    mtq & vnh --> |AND| jtf
    nbq & qjf --> |OR| kbj
    ngc & sdt --> |AND| rbk
    nhh & cdm --> |AND| vmf
    nhh & cdm --> |XOR| z27
    nhs & qvh --> |AND| vjd
    nhs & qvh --> |XOR| z21
    nmk & dsr --> |AND| qrt
    nmk & dsr --> |XOR| z01
    nnf & vbr --> |OR| hvg
    nnw & qnd --> |XOR| z25
    nqg & hbn --> |AND| wqc
    nqg & hbn --> |XOR| z08
    nsg & sdh --> |AND| nbq
    nss & vjd --> |OR| vss
    pfk & cmd --> |XOR| z35
    pht & dgj --> |OR| jmc
    pjj & wvn --> |OR| wpq
    pjt & ppp --> |XOR| z24
    ppp & pjt --> |AND| ptt
    ppw & jqs --> |OR| wjt
    ptt & bvn --> |OR| nnw
    qds & fcg --> |OR| vdc
    qkk & jmc --> |AND| hnj
    qnd & nnw --> |AND| gnv
    rbk & mdv --> |OR| spk
    rtw & wpq --> |AND| nbh
    rtw & wpq --> |XOR| z11
    rvb & cpg --> |AND| wtv
    rvb & cpg --> |XOR| z26
    scb & dnp --> |AND| dpq
    scb & dnp --> |XOR| z36
    sdh & nsg --> |XOR| z12
    sdt & ngc --> |XOR| z33
    skd & ssq --> |XOR| z02
    spk & bmh --> |XOR| z34
    srq & sdr --> |AND| dpm
    srq & sdr --> |XOR| z41
    ssq & skd --> |AND| nqw
    svv & cjg --> |OR| mmr
    tbp & tts --> |OR| dcd
    tcb & fgg --> |OR| nqg
    tcv & gqh --> |AND| cdk
    tjq & gwt --> |OR| jsj
    tvs & mkh --> |XOR| z31
    vmf & snj --> |OR| cfd
    vng & vnw --> |AND| fcg
    vng & vnw --> |XOR| z03
    vnh & mtq --> |XOR| z37
    vnn & qjh --> |AND| fgv
    vnn & qjh --> |XOR| z14
    vqk & kgh --> |OR| pmt
    vrk & hmt --> |OR| tpv
    vss & wnq --> |AND| tjq
    wjf & dcd --> |AND| hpm
    wjf & dcd --> |XOR| z43
    wjt & ftt --> |AND| htr
    wjt & ftt --> |XOR| z18
    wnq & vss --> |XOR| z22
    wqc & pvm --> |OR| kgr
    wrc & tgb --> |OR| pfk
    wtr & rwr --> |OR| tcv
    x00 & y00 --> |AND| dsr
    x00 & y00 --> |XOR| z00
    x01 & y01 --> |AND| hqh
    x01 & y01 --> |XOR| nmk
    x02 & y02 --> |XOR| ssq
    x03 & y03 --> |AND| qds
    x03 & y03 --> |XOR| vng
    x04 & y04 --> |AND| cjg
    x04 & y04 --> |XOR| krm
    x13 & y13 --> |XOR| nsd
    x14 & y14 --> |XOR| qjh
    x15 & y15 --> |AND| btb
    x15 & y15 --> |XOR| qnp
    x16 & y16 --> |XOR| wkn
    x17 & y17 --> |AND| ppw
    x17 & y17 --> |XOR| mhm
    x19 & y19 --> |AND| rwr
    x20 & y20 --> |XOR| gqh
    x22 & y22 --> |AND| gwt
    x23 & y23 --> |AND| cnp
    x23 & y23 --> |XOR| cnv
    x25 & y25 --> |AND| gqt
    x26 & y26 --> |AND| dvb
    x27 & y27 --> |XOR| nhh
    x28 & y28 --> |AND| dgj
    x29 & y29 --> |AND| ddt
    x29 & y29 --> |XOR| qkk
    x30 & y30 --> |AND| kqh
    x33 & y33 --> |XOR| ngc
    x34 & y34 --> |AND| tgb
    x34 & y34 --> |XOR| bmh
    x37 & y37 --> |AND| jdk
    x40 & y40 --> |XOR| bwc
    x42 & y42 --> |AND| tbp
    x42 & y42 --> |XOR| kbv
    x44 & y44 --> |XOR| cbq
    y02 & x02 --> |AND| jmp
    y05 & x05 --> |AND| hmt
    y05 & x05 --> |XOR| cgr
    y06 & x06 --> |AND| kgh
    y06 & x06 --> |XOR| jpp
    y07 & x07 --> |AND| tcb
    y07 & x07 --> |XOR| cwn
    y08 & x08 --> |AND| pvm
    y08 & x08 --> |XOR| hbn
    y09 & x09 --> |AND| nnf
    y09 & x09 --> |XOR| fvp
    y10 & x10 --> |AND| pjj
    y10 & x10 --> |XOR| gtg
    y11 & x11 --> |AND| kwf
    y11 & x11 --> |XOR| rtw
    y12 & x12 --> |AND| qjf
    y12 & x12 --> |XOR| nsg
    y13 & x13 --> |AND| bfw
    y14 & x14 --> |AND| jhb
    y16 & x16 --> |AND| qsd
    y18 & x18 --> |AND| kdm
    y18 & x18 --> |XOR| ftt
    y19 & x19 --> |XOR| bjm
    y20 & x20 --> |AND| rmn
    y21 & x21 --> |AND| nss
    y21 & x21 --> |XOR| qvh
    y22 & x22 --> |XOR| wnq
    y24 & x24 --> |AND| bvn
    y24 & x24 --> |XOR| ppp
    y25 & x25 --> |XOR| qnd
    y26 & x26 --> |XOR| cpg
    y27 & x27 --> |AND| snj
    y28 & x28 --> |XOR| cqd
    y30 & x30 --> |XOR| ddn
    y31 & x31 --> |AND| mds
    y31 & x31 --> |XOR| tvs
    y32 & x32 --> |AND| dnw
    y32 & x32 --> |XOR| cwr
    y33 & x33 --> |AND| mdv
    y35 & x35 --> |AND| wtc
    y35 & x35 --> |XOR| cmd
    y36 & x36 --> |AND| hsc
    y36 & x36 --> |XOR| scb
    y37 & x37 --> |XOR| vnh
    y38 & x38 --> |AND| gcn
    y38 & x38 --> |XOR| dmh
    y39 & x39 --> |AND| sms
    y39 & x39 --> |XOR| bss
    y40 & x40 --> |AND| rpm
    y41 & x41 --> |AND| pqq
    y41 & x41 --> |XOR| sdr
    y43 & x43 --> |AND| nhq
    y43 & x43 --> |XOR| wjf
    y44 & x44 --> |AND| rqv
